# Generated by Django 3.2.5 on 2021-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prodimg',
            field=models.ImageField(default='', upload_to='prodimages'),
            preserve_default=False,
        ),
    ]
