# Generated by Django 3.2.5 on 2021-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0005_auto_20210721_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sn',
            field=models.IntegerField(default=0),
        ),
    ]
