# Generated by Django 3.2.5 on 2021-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0006_products_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
